### ISSUE TITLE
Install quasar js

### ISSUE THREAD

**Issue by raphaeldealmeida** [alexjoverm/v-runtime-template#16]
How can I install in Quasar JS?

**Comment by coderpradp** [comment]
@raphaeldealmeida 
1. `npm install v-runtime-template`
2. Edit `quasar.conf.js`:
```js
  ...
  build: {
    ...
    vueCompiler: true,
    ...
  },
  ...
```
3. Use it as described in this [Usage Guide](https://github.com/alexjoverm/v-runtime-template#usage)
