### ISSUE TITLE
You library is amazing :)

### ISSUE THREAD

**Issue by carmas123** [alexjoverm/v-runtime-template#18]
This issue is only to congrats with you.

I've only a problem with this library, I use it in nuxt and one page loaded all work fine but if I try to refresh the page I got this warning:

>  The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.

Thanks you so much.

**Comment by alexjoverm** [comment]
Hi @carmas123 !!!

Thanks a lot for the compliments :). I hope you find it useful.

Yeah, we use it on Nuxt as well and see that warning. Not sure if it could be solved, but so far didn't give us any problem
