### ISSUE TITLE
Feature Request: Pass props to the template

### ISSUE THREAD

**Issue by Pyro979** [alexjoverm/v-runtime-template#22]
It'd be nice if we can pass specific props to the template - for example if you're looping through an object and each object needs to be passed in. 

Since we can't just pass arbitrary props to the component, I'm proposing we pass in an object with the props, which then merges with the parent's data & props to be passed to the template.

Example:
```
<div v-for="person in people" :key="person.id">
  <v-runtime-template :template="fancy_name" :template_props="{name: person.name, id: person.id}"/>
</div>
```

**Comment by alexjoverm** [comment]
Fixed by 1.9.0
