### ISSUE TITLE
Update release on npm

### ISSUE THREAD

**Issue by Duncank** [alexjoverm/v-runtime-template#23]
I'm having some problems with mixins and duplicated props, which seems to be fixed in #20, but the new version is not available on npm yet. Any chance of pushing the update there as well?

**Comment by Solinx** [comment]
In the meantime you can use this to get the latest version straight from GitHub.
`yarn add https://github.com/alexjoverm/v-runtime-template`

**Comment by alexjoverm** [comment]
Hey guys, it was supposed to be there already. Just in case, it's published again in 1.6.1 :)
