### ISSUE TITLE
runtimeCompiler option

### ISSUE THREAD

**Issue by duebbert** [alexjoverm/v-runtime-template#28]
Just a small improvement suggestion for the documentation. If using vue-cli, then the runtimeCompiler option can be used: https://cli.vuejs.org/config/#runtimecompiler

Currently in Readme:
```
// vue.config.js
module.exports = {
  configureWebpack: {
    resolve: {
      alias: {
        vue$: "vue/dist/vue.common",
      },
    },
  },
};
```

Instead you can use:
```
// vue.config.js
module.exports = {
  runtimeCompiler: true
};
```

**Comment by alexjoverm** [comment]
Done! Thanks :)
