### ISSUE TITLE
Bug on building methods

### ISSUE THREAD

**Issue by carmas123** [alexjoverm/v-runtime-template#34]
Hi I think that there is a bug when we build passthrough methods.

`Object.keys(methods).forEach(e => {if(typeof this.$options.methods[e]==="undefined") passthrough.methods[e] = methods[e];} );`

We need to change into 
`Object.keys(methods).forEach(e => {if(typeof this.$options.methods==="undefined" || typeof this.$options.methods[e]==="undefined") passthrough.methods[e] = methods[e];} );`

**Comment by rkhunter** [comment]
:+1:

**Comment by alexjoverm** [comment]
Fixed on 1.7.1 6289c88c6812df2037f3e138e35fad75c4fd71cc
