### ISSUE TITLE
Template allows multiple children but renders only the first

### ISSUE THREAD

**Issue by vflyson** [alexjoverm/v-runtime-template#36]
This happens with no warning and took me a minute to debug without error/warning messages in the console.

In a nutshell, if `template: "<b>a</b>"` then it's all good, but if `template: "<a>b</a><b>a</b>"`, then only the first node (`<a>b</a>`) will be rendered, with no warning regarding wrapping templates into one root node being a requirement.

**Comment by alexjoverm** [comment]
Yes, there must be one single root component just as Vue templates
