### ISSUE TITLE
Create a directive instead of component

### ISSUE THREAD

**Issue by padcom** [alexjoverm/v-runtime-template#4]
Just a thought, mainly inspired by the component name (v-render-template). Since ```v-html``` is a directive maybe it'd make sense to just create another directive instead of a full component?

Would that be at all possible?

I can clearly imagine myself using something like that instead of ```v-html```

```
<div v-render-template="tpl" />
```

**Comment by alexjoverm** [comment]
It might be an option, not sure though, it'd require some investigation. However, since it's already implemented as a component, better to keep it like it. Components gives you more control to extend them

**Comment by MrBasque** [comment]
exactly my idea @padcom, it would definitely make life simpler ;-)
