### ISSUE TITLE
Not render props, methods inside..in components :: nuxt

### ISSUE THREAD

**Issue by davizxtr** [alexjoverm/v-runtime-template#47]
Hi

Congratulations for the component!

I'm using nuxt and it works properly with the template for database.
I can not show props, methods ... inside of the components

Nuxt.config
![image](https://user-images.githubusercontent.com/37248385/57466003-0e21fe80-7280-11e9-9de1-e91591d90dad.png)

Page script
![image](https://user-images.githubusercontent.com/37248385/57466094-3b6eac80-7280-11e9-9d36-0b8f96afb79e.png)

Page template
![image](https://user-images.githubusercontent.com/37248385/57466127-50e3d680-7280-11e9-88c3-854170e4d0a9.png)

To test mode...
I try to show the prop title_test inside of div and it does not work

More thanks!!

**Comment by alexjoverm** [comment]
Hey! I've tried your code and it works for me, can you try again?
