### ISSUE TITLE
[NUXT] Error: Cannot read property '$metaInfo' of undefined

### ISSUE THREAD

**Issue by mistGit** [alexjoverm/v-runtime-template#49]
I am using latest Nuxt (2.8.1). I have installed v-runtime-template and when I try to use it in my template as a component and pass it the string that should be compiled, I get this error.

**### Cannot read property '$metaInfo' of undefined.**

I also added '`config.resolve.alias["vue"] = "vue/dist/vue.common";`' into the nuxt config but it had no effect.

Any ideas about what might be causing this error and how to fix it?

Node version: 10.15.3

**Comment by alexjoverm** [comment]
Fixed on 1.7.1 6289c88c6812df2037f3e138e35fad75c4fd71cc
