### ISSUE TITLE
How can I debug demo code on my computer?

### ISSUE THREAD

**Issue by glikoz** [alexjoverm/v-runtime-template#7]
I know question is a little of-topic, but I admired your work, you are filling the most important point for me.
I want to extend your code with router and vuex implemantation:

- 1. Each page (vue component),  and ,it's data will be served dynamically from server side,  
- 2. Page will be initialized with new VueComponent and its own data. 

(I saw vue-router dependency on demo code but it is not used)

But I could not run demo code on my local machine
npm run 
npm start 
yarn start
static-serve
vue-serve
no one works, how can I debug demo code from my computer.

**Comment by alexjoverm** [comment]
Easiest way: 

 - Install parcel (npm install parcel-bundler)
 - Create a dev script on the package.json

```js
// package.json
{
	"scripts": {
		"dev": "parcel index.html"
	}
}
```

And run npm run dev.


Another option: create a new project using vue-cli and copy the App.vue and AppMessage.vue components
