### ISSUE TITLE
Accessing v-for loop vars from v-runtime-template

### ISSUE THREAD

**Issue by hannesaasamets** [alexjoverm/v-runtime-template#9]
Is it possible to use the `v-for` variables inside the `v-runtime-template` along the following lines:
```
<div v-for="row in rows">
  <v-runtime-template :template="'<p>{{row}}</p>'" />
</div>
```
https://codesandbox.io/s/01l5j73k90

**Comment by damey2011** [comment]
it doesnt work for me too

**Comment by alexjoverm** [comment]
I don't think that's possible, since the `row` variable scope is created by the template as a "temporary" scope, but v-runtime-template has access only to the component scope.

A workaround, can be to create a component for the items on the list. In that way, the row would be in the component scope:

```
<Row :row="row" v-for="row in rows">
```

**Comment by alexjoverm** [comment]
Or even to place the for loop [within the template](https://codesandbox.io/s/3vpp38o8lq):

```html
<template>
  <div id="app">
    <v-runtime-template :template="tmplt2" />
  </div>
</template>

<script>
import VRuntimeTemplate from "v-runtime-template";

export default {
  name: "App",
  components: {
    VRuntimeTemplate,
  },
  data() {
    return {
      rows: [1,2,3],
      tmplt2: `
        <div>
          <p v-for="row in rows">{{ row }}</p>
        </div>
      `
	}
  }
}
```

**Comment by alexjoverm** [comment]
Any option is valid as long as the template access only component instance variables

**Comment by ibalaji777** [comment]
This can access by index
rows[index] instead of row
